---
- name: Setup BIND9 DNS Server on Ubuntu 24.04
  hosts: dns_servers
  become: true
  become_user: root
  vars_files:
    - vars/dns_config.yaml

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install BIND9 packages
      ansible.builtin.apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
          - dnsutils
        state: present

    - name: Create BIND9 configuration directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: bind
        group: bind
        mode: '0755'
      loop:
        - /etc/bind/zones
        - /var/log/bind

    - name: Configure BIND9 named.conf.options
      ansible.builtin.template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: bind
        group: bind
        mode: '0644'
      notify: restart bind9

    - name: Configure BIND9 named.conf.local
      ansible.builtin.template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: bind
        group: bind
        mode: '0644'
      notify: restart bind9

    - name: Create forward zone files
      ansible.builtin.template:
        src: templates/forward.zone.j2
        dest: "/etc/bind/zones/db.{{ item.domain }}"
        owner: bind
        group: bind
        mode: '0644'
      loop: "{{ dns_zones }}"
      notify: restart bind9

    - name: Create reverse zone files
      ansible.builtin.template:
        src: templates/reverse.zone.j2
        dest: "/etc/bind/zones/db.{{ item.reverse_zone }}"
        owner: bind
        group: bind
        mode: '0644'
      loop: "{{ dns_zones }}"
      when: item.reverse_zone is defined
      notify: restart bind9

    - name: Configure systemd for BIND9 logging
      ansible.builtin.file:
        path: /var/log/bind
        state: directory
        owner: bind
        group: bind
        mode: '0755'

    - name: Enable and start BIND9 service
      ansible.builtin.systemd:
        name: named
        enabled: true
        state: started

    - name: Configure UFW firewall for DNS
      ansible.builtin.ufw:
        rule: allow
        port: 53
        proto: "{{ item }}"
      loop:
        - tcp
        - udp
      when: configure_firewall | default(false)

  handlers:
    - name: restart bind9
      ansible.builtin.systemd:
        name: named
        state: restarted

    - name: reload bind9
      ansible.builtin.systemd:
        name: named
        state: reloaded
