- name: 'Deploy containers'

  hosts: 'local'
  connection: local
  tasks:
  - name: 'Create container 1'
    community.general.proxmox:
      vmid: '1000'
      api_user: 'ansible@pam'
      api_token_id: 'ans_001'
      api_token_secret: 'f1af111d-a6d3-4c81-b8d2-042fde52b5ce'
      api_host: '172.16.1.10'
      password: 'admin'
      hostname: 'pve-ubuntu-01'
      node: 'master'
      cores: '1'
      cpus: '1'
      cpuunits: '1000'
      ostemplate: 'storage:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
      disk: 'storage:8'
      memory: '512'
      nameserver: '172.16.1.1'
      netif: '{"net0":"name=eth0,ip=172.16.1.90/32,ip6=dhcp,bridge=vmbr0,gw=172.16.1.1"}'
      searchdomain: 'ubuntu-01.cluster.proxmox.local'
      state: 'present'
      onboot: 'true'

  - name: 'Create container 2'
    community.general.proxmox:
      vmid: '1001'
      api_user: 'ansible@pam'
      api_token_id: 'ans_001'
      api_token_secret: 'f1af111d-a6d3-4c81-b8d2-042fde52b5ce'
      api_host: '172.16.1.10'
      password: 'admin'
      hostname: 'pve-ubuntu-02'
      node: 'master'
      cores: '1'
      cpus: '1'
      cpuunits: '1000'
      ostemplate: 'storage:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
      disk: 'storage:8'
      memory: '512'
      nameserver: '172.16.1.1'
      netif: '{"net0":"name=eth0,ip=172.16.1.91/32,ip6=dhcp,bridge=vmbr0,gw=172.16.1.1"}'
      searchdomain: 'ubuntu-02.cluster.proxmox.local'
      state: 'present'

  - name: 'Create container 3'
    community.general.proxmox:
      vmid: '1002'
      api_user: 'ansible@pam'
      api_token_id: 'ans_001'
      api_token_secret: 'f1af111d-a6d3-4c81-b8d2-042fde52b5ce'
      api_host: '172.16.1.10'
      password: 'admin'
      hostname: 'pve-ubuntu-03'
      node: 'master'
      cores: '1'
      cpus: '1'
      cpuunits: '1000'
      ostemplate: 'storage:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
      disk: 'storage:8'
      memory: '512'
      nameserver: '172.16.1.1'
      netif: '{"net0":"name=eth0,ip=172.16.1.92/32,ip6=dhcp,bridge=vmbr0,gw=172.16.1.1"}'
      searchdomain: 'ubuntu-03.cluster.proxmox.local'
      state: 'present'

  - name: 'Start container 1'
    community.general.proxmox:
      vmid: 1000
      api_user: 'ansible@pam'
      api_token_id: 'ans_001'
      api_token_secret: 'f1af111d-a6d3-4c81-b8d2-042fde52b5ce'
      api_host: '172.16.1.10'
      state: 'started'

  - name: 'Start container 2'
    community.general.proxmox:
      vmid: 1001
      api_user: 'ansible@pam'
      api_token_id: 'ans_001'
      api_token_secret: 'f1af111d-a6d3-4c81-b8d2-042fde52b5ce'
      api_host: '172.16.1.10'
      state: 'started'

  - name: 'Start container 3'
    community.general.proxmox:
      vmid: 1002
      api_user: 'ansible@pam'
      api_token_id: 'ans_001'
      api_token_secret: 'f1af111d-a6d3-4c81-b8d2-042fde52b5ce'
      api_host: '172.16.1.10'
      state: 'started'
