- name: 'Deploy Nginx'

  hosts: 'webservers-debian'
  become: true
  become_user: root

  tasks:
    - name: 'Update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: "Install dependencies"
      ansible.builtin.apt:
        pkg:
          - curl
          - ca-certificates
          - gnupg2
          - wget
          - lsb-release
          - debian-archive-keyring
          - python3
          - python3-venv
          - libaugeas0
        update_cache: true

    - name: 'Add Nginx repository'
      ansible.builtin.shell: |
        curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
        echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian `lsb_release -cs` nginx" | tee /etc/apt/sources.list.d/nginx.list
        echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" | tee /etc/apt/preferences.d/99nginx
      args:
        executable: /bin/bash

    - name: 'Install nginx'
      ansible.builtin.apt:
        pkg:
          - nginx
        update_cache: true

    - name: 'Setup certbot'
      ansible.builtin.shell: |
        python3 -m venv /opt/certbot/
        /opt/certbot/bin/pip install --upgrade pip
        /opt/certbot/bin/pip install certbot certbot-nginx
        ln -s /opt/certbot/bin/certbot /usr/bin/certbot
      args:
        executable: /bin/bash
