- name: 'Deploy Jenkins'

  hosts: 'proxmox-ubuntu-cts-lead'
  tasks:
    - name: 'Update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: 'Install dependencies'
      ansible.builtin.apt:
        pkg:
          - curl
          - fontconfig
          - openjdk-11-jre
          - git
        update_cache: true

    - name: 'Download Jenkins GPG key'
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: 'Add Jenkins repository'
      ansible.builtin.copy:
        content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        dest: /etc/apt/sources.list.d/jenkins.list
        mode: '0644'

    - name: 'Install Jenkins'
      ansible.builtin.apt:
        name: jenkins
        update_cache: true

    - name: 'Start Jenkins'
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true

    - name: 'Read the initial admin password file'
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: password

    - name: 'Print the password'
      ansible.builtin.debug:
        msg: 'Finish the setup at http://{{ ansible_default_ipv4.address }}:8080 with password {{ password.content | b64decode | trim }}'
