- name: 'Deploy Nginx'

  hosts: 'webservers-debian'
  become: true
  become_user: root

  tasks:
    - name: 'Update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: "Install dependencies"
      ansible.builtin.apt:
        pkg:
          - curl
          - ca-certificates
          - gnupg2
          - wget
          - lsb-release
          - debian-archive-keyring
          - python3
          - python3-venv
          - libaugeas0
        update_cache: true

    - name: 'Download Nginx GPG key'
      ansible.builtin.get_url:
        url: https://nginx.org/keys/nginx_signing.key
        dest: /tmp/nginx_signing.key
        mode: '0644'

    - name: 'Dearmor Nginx GPG key'
      ansible.builtin.shell: |
        set -o pipefail
        gpg --dearmor < /tmp/nginx_signing.key > /usr/share/keyrings/nginx-archive-keyring.gpg
      args:
        executable: /bin/bash
        creates: /usr/share/keyrings/nginx-archive-keyring.gpg

    - name: 'Add Nginx repository'
      ansible.builtin.copy:
        content: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian {{ ansible_distribution_release }} nginx"
        dest: /etc/apt/sources.list.d/nginx.list
        mode: '0644'

    - name: 'Add Nginx APT preferences'
      ansible.builtin.copy:
        content: |
          Package: *
          Pin: origin nginx.org
          Pin: release o=nginx
          Pin-Priority: 900
        dest: /etc/apt/preferences.d/99nginx
        mode: '0644'

    - name: 'Install nginx'
      ansible.builtin.apt:
        pkg:
          - nginx
        update_cache: true

    - name: 'Setup certbot'
      ansible.builtin.shell: |
        python3 -m venv /opt/certbot/
        /opt/certbot/bin/pip install --upgrade pip
        /opt/certbot/bin/pip install certbot certbot-nginx
        ln -sf /opt/certbot/bin/certbot /usr/bin/certbot
      args:
        executable: /bin/bash
        creates: /opt/certbot/bin/certbot
