- name: 'Basic Ubuntu/Debian server setup'

  hosts: 'hetzner'
  become: true
  become_user: root

  tasks:
    - name: 'Update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: "Install dependencies"
      ansible.builtin.apt:
        pkg:
          - curl
          - ca-certificates
          - git
          - gnupg
          - wget
          - apt-transport-https
          - software-properties-common
          - htop
          - zsh
        update_cache: true

    - name: 'Add Docker repository'
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: 'Install Docker'
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: "Create management user"
      ansible.builtin.user:
        append: yes
        shell: /bin/zsh
        groups: docker,sudo,users
        name: cc
        create_home: true

    - name: 'Get zsh plugins'
      ansible.builtin.shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
      args:
        executable: /bin/bash
      become: true
      become_user: cc
