- name: 'Setup build VM for Azure DevOps'

  hosts: 'builders'
  become: true
  become_user: root

  tasks:
    - name: 'Update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: "Install dependencies"
      ansible.builtin.apt:
        pkg:
          - curl
          - ca-certificates
          - git
          - gnupg
          - wget
          - apt-transport-https
          - software-properties-common
          - htop
          - zsh
        update_cache: true

    - name: 'Add Docker repository'
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: 'Install Docker'
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: 'Install kubectl'
      ansible.builtin.shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash

    - name: 'Install Helm'
      ansible.builtin.shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        executable: /bin/bash

    - name: 'Add Microsoft repository'
      ansible.builtin.shell: |
        wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
        dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
      args:
        executable: /bin/bash

    - name: 'Install Powershell'
      ansible.builtin.apt:
        name: powershell
        update_cache: true

    - name: 'Create DevOps user'
      ansible.builtin.user:
        append: yes
        groups: docker
        name: svc_devops

    - name: "Create management user"
      ansible.builtin.user:
        append: yes
        shell: /bin/zsh
        groups: docker,sudo,users
        name: cc
        create_home: true
