- name: 'Setup build VM for Azure DevOps'

  hosts: 'builders'
  become: true
  become_user: root

  tasks:
    - name: 'Update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: "Install dependencies"
      ansible.builtin.apt:
        pkg:
          - curl
          - ca-certificates
          - git
          - gnupg
          - wget
          - apt-transport-https
          - software-properties-common
          - htop
          - zsh
        update_cache: true

    - name: 'Create keyrings directory'
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: 'Download Docker GPG key'
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: 'Dearmor Docker GPG key'
      ansible.builtin.shell: |
        set -o pipefail
        gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        executable: /bin/bash
        creates: /etc/apt/keyrings/docker.gpg

    - name: 'Add Docker repository'
      ansible.builtin.copy:
        content: >-
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'

    - name: 'Install Docker'
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: 'Get kubectl stable version'
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: true
      register: kubectl_version

    - name: 'Download kubectl'
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        owner: root
        group: root

    - name: 'Download Helm install script'
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: 'Install Helm'
      ansible.builtin.command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: 'Download Microsoft repository package'
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"
        dest: /tmp/packages-microsoft-prod.deb
        mode: '0644'

    - name: 'Install Microsoft repository'
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb

    - name: 'Remove Microsoft repository package'
      ansible.builtin.file:
        path: /tmp/packages-microsoft-prod.deb
        state: absent

    - name: 'Install Powershell'
      ansible.builtin.apt:
        name: powershell
        update_cache: true

    - name: 'Create DevOps user'
      ansible.builtin.user:
        append: true
        groups: docker
        name: svc_devops

    - name: "Create management user"
      ansible.builtin.user:
        append: true
        shell: /bin/zsh
        groups: docker,sudo,users
        name: cc
        create_home: true
